"""add_strategy_backtest_audit_paper_risk_tables

Revision ID: 5398ee7db1cf
Revises: d7d3b819bda7
Create Date: 2026-04-27 17:50:25.850298

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5398ee7db1cf'
down_revision: Union[str, Sequence[str], None] = 'd7d3b819bda7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
