"""initial_data_models

Revision ID: d7d3b819bda7
Revises: 
Create Date: 2026-04-27 14:51:32.944840

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd7d3b819bda7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instruments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('exchange', sa.String(length=8), nullable=False, comment='SH or SZ'),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_instruments_symbol'), 'instruments', ['symbol'], unique=True)
    op.create_table('trading_calendar',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('is_trading_day', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('date')
    )
    op.create_table('daily_bars',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('open', sa.Float(), nullable=False),
    sa.Column('high', sa.Float(), nullable=False),
    sa.Column('low', sa.Float(), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('volume', sa.Float(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('adj_close', sa.Float(), nullable=True),
    sa.Column('data_source', sa.String(length=64), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('instrument_id', 'trade_date', name='uq_instrument_trade_date')
    )
    op.create_index('ix_daily_bars_instrument_date', 'daily_bars', ['instrument_id', 'trade_date'], unique=False)
    op.create_index('ix_daily_bars_trade_date', 'daily_bars', ['trade_date'], unique=False)
    op.create_table('data_quality_reports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('check_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('missing_dates', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('price_jumps', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('zero_volume_dates', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('overall_status', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_quality_instrument_date', 'data_quality_reports', ['instrument_id', 'check_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_quality_instrument_date', table_name='data_quality_reports')
    op.drop_table('data_quality_reports')
    op.drop_index('ix_daily_bars_trade_date', table_name='daily_bars')
    op.drop_index('ix_daily_bars_instrument_date', table_name='daily_bars')
    op.drop_table('daily_bars')
    op.drop_table('trading_calendar')
    op.drop_index(op.f('ix_instruments_symbol'), table_name='instruments')
    op.drop_table('instruments')
    # ### end Alembic commands ###
